import { createSlice } from '@reduxjs/toolkit'

// Create a slice for managing user-related state in Redux
export const userSlice = createSlice({
    name: 'user', // Name of the slice
    initialState: { // Initial state of the slice
        user: {}, // User data
        isLoggedIn: false, // Boolean indicating whether the user is logged in or not
        token: null, // User token
        recentlyViewedArtist: ["0kbYTNQb4Pb1rPbbaF0pT4","2YVF0Ou5zIc4mpgtLIlGN0", "4Z5eM7HLu4b0LAKrywoWR2","5QqCSh9Ri3B7Tw6HNQkPQH","02dokIaBFwqSfAFyU8xWWZ","02dokIaBFwqSfAFyU8xWWZ","02dokIaBFwqSfAFyU8xWWZ","02dokIaBFwqSfAFyU8xWWZ","02dokIaBFwqSfAFyU8xWWZ" ], // PLACEHOLDER Recently Viewed Artists List of Spotify Artist IDs
    },
    reducers: {
        // Reducer function for handling user login
        login: (state, action) => {
            state.user = action.payload.user; // Update user data
            state.isLoggedIn = action.payload.isLoggedIn; // Update login status
            state.token = action.payload.token; // Update user token

            localStorage.setItem('token', action.payload.token);
        },
        // Reducer function for handling user logout
        logout: (state) => {

            state.user = null
            state.isLoggedIn = false
            state.token = null
            state.currentUser = null

            localStorage.removeItem('token');
        },
        // Reducer function for setting the current user
        setCurrentUser: (state, action) => {
            state.currentUser = action.payload.user; // Set current user
        },
        addRecentlyViewedArtist: (state, action) => {
            // Add artist to recently viewed artists (call when navigating to artist page)
            state.recentlyViewedArtist.push(action.payload.artist);
        },
        removeRecentlyViewedArtist: (state) => {
            // Remove least recent artist from recently viewed artists (call when artist list = 10)
            state.recentlyViewedArtist.shift();
        },
    },
});

// Export actions for user login, logout, and setting current user
export const { login, logout, setCurrentUser, addRecentlyViewedArtist, removeRecentlyViewedArtist } = userSlice.actions;


export const selectUser = (state) => state.user;
export const selectToken = (state) => state.token;
export const selectRecentlyViewedArtists = (state) => state.recentlyViewedArtist; // Selector for recently viewed artists

// Export the reducer function generated by createSlice
export default userSlice.reducer;
