import { createSlice } from '@reduxjs/toolkit'

// Create a slice for managing user-related state in Redux
export const userSlice = createSlice({
    name: 'user', // Name of the slice
    initialState: { // Initial state of the slice
        user: null, // User data
        isLoggedIn: false, // Boolean indicating whether the user is logged in or not
        token: null // User token
    },
    reducers: {
        // Reducer function for handling user login
        login: (state, action) => {
            state.user = action.payload.user; // Update user data
            state.isLoggedIn = action.payload.isLoggedIn; // Update login status
            state.token = action.payload.token; // Update user token
        },
        // Reducer function for handling user logout
        logout: (state) => {
            state.user = null; // Reset user data
            state.isLoggedIn = false; // Set login status to false
        },
        // Reducer function for setting the current user
        setCurrentUser: (state, action) => {
            state.currentUser = action.payload.user; // Set current user
        },
    },
});

// Export actions for user login, logout, and setting current user
export const { login, logout, setCurrentUser } = userSlice.actions;

// Selectors for accessing user state
export const selectUser = (state) => state.user; // Selects the user slice from the state

// Export the reducer function generated by createSlice
export default userSlice.reducer;
