import { createSlice } from '@reduxjs/toolkit'

// Create a slice for managing user-related state in Redux
export const userSlice = createSlice({
    name: 'user', // Name of the slice
    initialState: { // Initial state of the slice
        user: {}, // User data
        isLoggedIn: false, // Boolean indicating whether the user is logged in or not
        token: null // User token
    },
    reducers: {
        // Reducer function for handling user login
        login: (state, action) => {
            state.user = action.payload.user; // Update user data
            state.isLoggedIn = action.payload.isLoggedIn; // Update login status
            state.token = action.payload.token; // Update user token

            localStorage.setItem('token', action.payload.token);
        },
        // Reducer function for handling user logout
        logout: (state) => {

            state.user = null
            state.isLoggedIn = false
            state.token = null

            localStorage.removeItem('token');
        },
        // Reducer function for setting the current user
        setCurrentUser: (state, action) => {
            state.currentUser = action.payload.user; // Set current user
        },
    },
});

// Export actions for user login, logout, and setting current user
export const { login, logout, setCurrentUser } = userSlice.actions;


export const selectUser = (state) => state.user;
export const selectToken = (state) => state.token;


// Export the reducer function generated by createSlice
export default userSlice.reducer;
